[package]
name = "lexer-framework"
version = "0.1.0"
edition = "2021"

[lib]
name = "lexer_framework"
path = "src/lib.rs"

[features]
default = []
streaming = []

[dependencies]
common-framework = { path = "../common-framework" }

